---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - cluster-batch.beer1.com
  resources:
  - clusterjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster-batch.beer1.com
  resources:
  - clusterjobs/finalizers
  verbs:
  - update
- apiGroups:
  - cluster-batch.beer1.com
  resources:
  - clusterjobs/status
  verbs:
  - get
  - patch
  - update
